#include <stdio.h>
#include <stdbool.h>
#include <stdlib.h>
#include <memory.h>
#include "main.h"
#include <unistd.h>
#include <sys/wait.h>
#include <time.h>
#include <errno.h>
#include <sys/times.h>
#include <ctype.h>
#include <fcntl.h>